export const browserCoreExamples = [
  "enclaws browser status",
  "enclaws browser start",
  "enclaws browser stop",
  "enclaws browser tabs",
  "enclaws browser open https://example.com",
  "enclaws browser focus abcd1234",
  "enclaws browser close abcd1234",
  "enclaws browser screenshot",
  "enclaws browser screenshot --full-page",
  "enclaws browser screenshot --ref 12",
  "enclaws browser snapshot",
  "enclaws browser snapshot --format aria --limit 200",
  "enclaws browser snapshot --efficient",
  "enclaws browser snapshot --labels",
];

export const browserActionExamples = [
  "enclaws browser navigate https://example.com",
  "enclaws browser resize 1280 720",
  "enclaws browser click 12 --double",
  'enclaws browser type 23 "hello" --submit',
  "enclaws browser press Enter",
  "enclaws browser hover 44",
  "enclaws browser drag 10 11",
  "enclaws browser select 9 OptionA OptionB",
  "enclaws browser upload /tmp/openclaw/uploads/file.pdf",
  'enclaws browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "enclaws browser dialog --accept",
  'enclaws browser wait --text "Done"',
  "enclaws browser evaluate --fn '(el) => el.textContent' --ref 7",
  "enclaws browser console --level error",
  "enclaws browser pdf",
];
