/**
 * Blocked input patterns — inlined as a TS constant so it survives bundling (tsdown).
 * Source of truth: keep this file in sync with any external pattern list.
 *
 * One regex string per entry (case-insensitive matching applied at runtime).
 */

export const BLOCKED_PATTERN_SOURCES: readonly string[] = [

  // ── File deletion & overwrite ──
  "rm\\s+-rf",
  "rm\\s+-f",
  "rm\\s+-r",
  "\\brmdir\\b",
  "\\bunlink\\b",
  "\\bshred\\b",
  ">\\s*\\/dev\\/sda",
  "\\bdd\\s+if=",
  "\\bmkfs\\b",
  "\\bmkfs\\.ext4\\b",
  "\\bmkfs\\.xfs\\b",
  "\\bwipefs\\b",
  "\\btruncate\\b",
  "\\bmv\\s+\\/\\*",
  "\\bcp\\s+\\/dev\\/null\\b",

  // ── System control & service management ──
  "\\bshutdown\\b",
  "\\breboot\\b",
  "\\bpoweroff\\b",
  "\\bhalt\\b",
  "\\binit\\s+[06]\\b",
  "\\bsystemctl\\s+stop\\b",
  "\\bsystemctl\\s+disable\\b",
  "\\bsystemctl\\s+restart\\b",
  "\\bsystemctl\\s+mask\\b",
  "\\bservice\\s+\\S+\\s+stop\\b",
  "\\bnginx\\s+-s\\s+(stop|quit)\\b",
  "\\bkill\\s+-9",
  "\\bkill\\b",
  "\\bkillall\\b",
  "\\bpkill\\b",
  "\\bxkill\\b",

  // ── User & permission management ──
  "\\buseradd\\b",
  "\\buserdel\\b",
  "\\busermod\\b",
  "\\bgroupadd\\b",
  "\\bgroupdel\\b",
  "\\bpasswd\\b",
  "\\bchpasswd\\b",
  "\\bchmod\\s+777\\b",
  "\\bchmod\\s+-R\\b",
  "\\bchown\\s+-R\\b",
  "\\bchgrp\\s+-R\\b",
  "\\bsudo\\b",
  "\\bsu\\s+-",
  "\\bvisudo\\b",
  "\\bsetfacl\\b",

  // ── Network & firewall ──
  "\\biptables\\s+-[FXD]\\b",
  "\\biptables\\s+-P\\s+\\S+\\s+DROP\\b",
  "\\bfirewalld\\b",
  "\\bfirewall-cmd\\b",
  "\\bufw\\s+(disable|allow)\\b",
  "\\bnft\\s+flush\\b",
  "\\broute\\s+(add|del)\\b",
  "\\bip\\s+route\\b",
  "\\bip\\s+link\\s+set\\s+\\S+\\s+down\\b",
  "\\bifdown\\b",
  "\\bifconfig\\s+\\S+\\s+down\\b",
  "\\bnmcli\\s+connection\\s+delete\\b",
  "\\bhostnamectl\\b",
  "\\bnc\\s+-l",
  "\\bncat\\b",
  "\\bsocat\\b",

  // ── SSH & remote access ──
  "\\bssh-keygen\\b",
  "\\bssh-copy-id\\b",
  "\\bsshd\\b",
  "authorized_keys",
  "\\/etc\\/ssh\\/sshd_config",

  // ── Sensitive file access ──
  "\\/etc\\/shadow",
  "\\/etc\\/passwd",
  "\\/etc\\/sudoers",
  "\\/etc\\/crontab",
  "\\.env\\b",
  "\\.ssh\\/",
  "\\.bash_history",
  "\\.git-credentials",
  "\\bid_rsa\\b",
  "\\.pem\\b",
  "\\.key\\b",
  "\\/proc\\/",
  "\\/sys\\/",

  // ── Scheduled tasks & autostart ──
  "\\bcrontab\\s+-[er]\\b",
  "\\/etc\\/cron\\.d\\/",
  "\\/etc\\/init\\.d\\/",
  "\\/etc\\/systemd\\/system\\/",
  "\\bat\\b\\s+",
  "\\bbatch\\b",

  // ── Dangerous shell tricks & bypasses ──
  ":\\(\\)\\{\\s*:\\|:&\\s*\\};:",
  "\\/dev\\/tcp\\/",
  "\\/dev\\/udp\\/",
  "\\beval\\b",
  "\\bexec\\b",
  "\\bsource\\b",
  "\\bnohup\\b",
  "\\bdisown\\b",
  "\\bscreen\\b",
  "\\btmux\\b",
  "base64\\s+-d\\s*\\|\\s*bash",
  "\\bpython\\s+-c\\b",
  "\\bperl\\s+-e\\b",
  "\\bruby\\s+-e\\b",
  "\\bphp\\s+-r\\b",
  "\\blua\\s+-e\\b",
  "\\bnode\\s+-e\\b",
  "\\bcurl\\b.*\\|\\s*bash",
  "\\bwget\\b.*\\|\\s*sh",
  "\\bcurl\\b.*\\|\\s*sh",

  // ── Restricted chat commands ──
  "^\\/restart\\b",
  "^\\/bash\\b",
  "^!\\s+",
  "^\\/config\\s+set\\b",
  "^\\/config\\s+unset\\b",
  "^\\/debug\\s+set\\b",
  "^\\/debug\\s+reset\\b",
  "^\\/mcp\\s+set\\b",
  "^\\/mcp\\s+unset\\b",
  "^\\/plugins\\s+install\\b",
  "^\\/plugins\\s+enable\\b",
  "^\\/plugins\\s+disable\\b",
  "^\\/kill\\s+all\\b",
  "^\\/allowlist\\s+add\\b",
  "^\\/allowlist\\s+remove\\b",
  "^\\/exec\\b",
  "^\\/elevated\\b",
];
